### ISSUE TITLE
Document ./maven-junit/xml.md is blank

### ISSUE THREAD

**Issue by sergsemenov** [netology-code/javaqa-code#1]
на документ ведет линк из лекции (32 слайд презентации https://netology.ru/profile/program/javaqa-4/lessons/21276/lesson_items/88349 ): 
![изображение](https://user-images.githubusercontent.com/60171896/75877288-638b5580-5e28-11ea-8fa5-f0c140d60228.png)
@coursar

**Comment by coursar** [comment]
fixed
