### ISSUE TITLE
The method StaticsService#calculate has incorrect Javadoc.

### ISSUE THREAD

**Issue by em0x5c** [netology-code/javaqa-code#4]
Javadoc of the method clearly states that it calculates and returns the index of max income,
but implementation returns the max value for the given "income" instead of the index of max element. Please take a look at the following code snippet:

```
  /**
   * Calculate index of max income
   *
   * @param incomes - array of incomes
   * @return - index of first max value
   */
  public long findMax(long[] incomes) {
    long current_max_index = 0;
    long current_max = incomes[0];
    for (long income : incomes)
      if (current_max < income)
        current_max = income;
        return current_max;
  }
```

It seems that the last line of code should contain only one TAB instead of two.

**Comment by coursar** [comment]
Yep, it's just sample of legacy bad written code.
